// Seconds on the shared demo clock. Each step is applied once by the server.
// 90s: chat 0–15, medication 15–39, fall 39–64, location 64–90.
// Keep 7s before fall confirmation and 13s for the route deviation replay.
export const TOUR_STEPS = [
  {
    at: 0,
    kind: "chat",
    role: "patient",
    tab: "guard",
    caption: "小安陪伴：说句话，就有回应。",
    op: "start",
  },
  {
    at: 3,
    kind: "chat",
    role: "patient",
    tab: "guard",
    caption: "用一句话找东西，支持文字与语音回放。",
    op: "chat",
  },
  {
    at: 10,
    kind: "chat",
    role: "patient",
    tab: "guard",
    caption: "事情得到回应，再开始今天的安排。",
    op: "found",
  },
  {
    at: 15,
    kind: "medication",
    role: "patient",
    tab: "guard",
    caption: "用药提醒到达，先确认收到。",
    op: "start",
  },
  {
    at: 19,
    kind: "medication",
    role: "patient",
    tab: "guard",
    caption: "“我知道了”只代表收到提醒。",
    op: "seen",
  },
  {
    at: 23,
    kind: "medication",
    role: "patient",
    tab: "guard",
    caption: "收到服药线索，仍等待家属核实。",
    op: "sequence",
  },
  {
    at: 27,
    kind: "medication",
    role: "family",
    tab: "board",
    detail: "medication",
    caption: "看护端查看线索，并确认这一次用药。",
    op: "view",
  },
  {
    at: 32,
    kind: "medication",
    role: "family",
    tab: "board",
    detail: "medication",
    caption: "模拟家属核实，统计随之更新。",
    op: "verify",
  },
  {
    at: 36,
    kind: "medication",
    role: "family",
    tab: "board",
    caption: "用药概览在首屏，待核实事项一眼可见。",
    op: "view",
  },
  {
    at: 39,
    kind: "fall",
    role: "family",
    tab: "guard",
    caption: "客厅正常行走 → 失衡 → 倒地 → 低位持续。",
    op: "start",
  },
  {
    at: 46,
    kind: "fall",
    role: "patient",
    tab: "guard",
    caption: "发现疑似跌倒，先向老人确认。",
    op: "view",
  },
  {
    at: 49,
    kind: "fall",
    role: "patient",
    tab: "guard",
    caption: "模拟老人明确求助，立即联络家人。",
    op: "help",
  },
  {
    at: 52,
    kind: "fall",
    role: "family",
    tab: "guard",
    caption: "通知送达后，家人明确接手。",
    op: "claim",
  },
  {
    at: 56,
    kind: "fall",
    role: "family",
    tab: "guard",
    caption: "记录到场进展，家人共享处理状态。",
    op: "arrive",
  },
  {
    at: 60,
    kind: "fall",
    role: "family",
    tab: "guard",
    caption: "记录模拟核实结果，保留完整处理过程。",
    op: "close",
  },
  {
    at: 64,
    kind: "location",
    role: "family",
    tab: "map",
    caption: "沿日常路线散步，随后转向陌生方向。",
    op: "start",
  },
  {
    at: 77,
    kind: "location",
    role: "patient",
    tab: "guard",
    caption: "连续偏离日常路线，向老人发起确认。",
    op: "view",
  },
  {
    at: 80,
    kind: "location",
    role: "family",
    tab: "map",
    caption: "家人接手寻找，查看最近有效位置。",
    op: "claim",
  },
  {
    at: 84,
    kind: "location",
    role: "family",
    tab: "map",
    caption: "模拟找到老人，记录陪同返回。",
    op: "arrive",
  },
  {
    at: 87,
    kind: "location",
    role: "family",
    tab: "map",
    caption: "寻找过程已记录，形成一次完整照护。",
    op: "close",
  },
  {
    at: 90,
    kind: "location",
    role: "family",
    tab: "board",
    caption: "演示完成：日常陪伴、用药核实、异常处置彼此连接。",
    op: "complete",
  },
];
export const TOUR_DURATION = 90;
